apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::262791824778:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1M4MQS4ZTK31X
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::262791824778:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::262791824778:user/aws-user1
      username: aws-user1

kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-15T09:30:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1434"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 838cb8a9-5b2e-4ad4-b014-b0188c9eb1eb
